### ISSUE TITLE
[story][RFC] v2.0 celebrating the 10 milion badges rendered

### ISSUE THREAD

**Issue by liuggio** [PUGX/badge-poser#88]
In about 20/25 days the number of rendered badges will reach the glorious number of 10.000.000.

In order to celebrate this great number, could be great introduce some love:

objective of 2.0: Copy snippet to clipboard, better search for a package, package perma-link.
- [x] Copy snippet to clipboard as #85.
- [x] improve package search similar to packagist search #86.
- [x] show in homepage the number of total badges rendered  #87
- [x] improve readability on unstable #81
